In [1]:
# Importing libraries
import pandas as pd

In [2]:
# reading data
nfl_data = pd.read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-04/standings.csv')

In [4]:
# check first few rows
nfl_data.head(3)

,team,team_name,year,wins,loss,points_for,points_against,points_differential,margin_of_victory,strength_of_schedule,simple_rating,offensive_ranking,defensive_ranking,playoffs,sb_winner
0,Miami,Dolphins,2000,11,5,323,226,97,6.1,1.0,7.1,0.0,7.1,Playoffs,No Superbowl
1,Indianapolis,Colts,2000,10,6,429,326,103,6.4,1.5,7.9,7.1,0.8,Playoffs,No Superbowl
2,New York,Jets,2000,9,7,321,321,0,0.0,3.5,3.5,1.4,2.2,No Playoffs,No Superbowl

In [5]:
# Check last rows
nfl_data.tail(3)

,team,team_name,year,wins,loss,points_for,points_against,points_differential,margin_of_victory,strength_of_schedule,simple_rating,offensive_ranking,defensive_ranking,playoffs,sb_winner
635,Seattle,Seahawks,2019,11,5,405,398,7,0.4,2.3,2.7,2.9,-0.2,Playoffs,No Superbowl
636,Los Angeles,Rams,2019,9,7,394,364,30,1.9,2.0,3.9,2.2,1.7,No Playoffs,No Superbowl
637,Arizona,Cardinals,2019,5,10,361,442,-81,-5.1,1.8,-3.2,-0.3,-2.9,No Playoffs,No Superbowl

In [7]:
# Summary stats
nfl_data.describe()

,year,wins,loss,points_for,points_against,points_differential,margin_of_victory,strength_of_schedule,simple_rating,offensive_ranking,defensive_ranking
count,638.000000,638.000000,638.000000,638.000000,638.000000,638.000000,638.000000,638.000000,6.380000e+02,638.000000,638.000000
mean,2009.528213,7.984326,7.984326,350.283699,350.283699,0.000000,-0.001881,0.001097,-6.682220e-17,-0.000157,-0.001097
std,5.757664,3.083822,3.083313,71.399067,59.546661,101.088938,6.323133,1.634369,6.200334e+00,4.340017,3.566280
min,2000.000000,0.000000,0.000000,161.000000,165.000000,-261.000000,-16.300000,-4.600000,-1.740000e+01,-11.700000,-9.800000
25%,2005.000000,6.000000,6.000000,299.000000,310.000000,-75.000000,-4.700000,-1.100000,-4.475000e+00,-3.175000,-2.400000
50%,2010.000000,8.000000,8.000000,348.000000,347.000000,1.500000,0.100000,0.000000,0.000000e+00,0.000000,0.100000
75%,2014.750000,10.000000,10.000000,396.000000,391.500000,72.750000,4.575000,1.200000,4.500000e+00,2.700000,2.500000
max,2019.000000,16.000000,16.000000,606.000000,517.000000,315.000000,19.700000,4.300000,2.010000e+01,15.900000,9.800000

In [17]:
nfl_data.to_csv('../data/nfl_data.csv', index=False)